<?php
    $output = '';

    // array met de data om de projectlijst te genereren
    $projects = [
        'project1' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project1', 'description' => 'Hallo ik ben project 1', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.'],
        'project2' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project2', 'description' => 'Hallo ik ben project 2', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.'],
        'project3' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project3', 'description' => 'Hallo ik ben project 3', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.'],
        'project4' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project4', 'description' => 'Hallo ik ben project 4', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.'],
        'project5' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project5', 'description' => 'Hallo ik ben project 5', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.'],
        'project6' => ['image' => 'images/tempimage.jpg', 'imageAlt' => 'projectImage', 'title' => 'project6', 'description' => 'Hallo ik ben project 6', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra odio sit amet euismod cursus. Donec eros enim, viverra sed bibendum eu, dictum non ante. Cras at tortor erat. Quisque ut augue in dui tempor pharetra. Integer a urna neque. Proin lobortis nibh ut volutpat rhoncus. Sed gravida nunc vitae massa pellentesque vulputate. Vivamus bibendum orci lorem, nec bibendum mauris dictum at. Donec vel mi ligula. Fusce fermentum, purus in rutrum ultrices, tortor velit malesuada sem, et lobortis magna urna et est. Maecenas ac iaculis magna. Morbi vulputate, tortor tincidunt rhoncus aliquam, libero justo pharetra quam, ac vulputate sapien lorem in neque. Vestibulum dapibus luctus eros, a congue sapien molestie vitae.
                        Mauris fringilla suscipit faucibus. Maecenas felis lorem, tempus non fermentum non, tincidunt vel magna. Duis viverra faucibus semper. Nulla gravida mauris id urna dignissim semper. Proin eleifend sed risus quis fringilla. Nullam nec dictum elit. Nulla feugiat eleifend leo at suscipit. Integer sit amet libero sit amet risus scelerisque rhoncus. Praesent quis auctor massa. Sed commodo aliquet ipsum lacinia molestie. Vestibulum vel accumsan ipsum, porta pulvinar est. Etiam lacus tortor, pulvinar id venenatis id, sollicitudin a erat.
                        Duis lacinia, mi a feugiat varius.']];
    
    // het genereeren van de uitklapbare projectlijst
    if(!empty($projects)){    
        foreach($projects as $project){
        // content voor in de preview
        $output .= '<div class="expandible"> <div class="expandiblePreview"> <img class="previewImage" src="'. $project['image'] .'" alt="'. $project['imageAlt'] .'"> <h2>'. $project['title'] .'</h2><p class="previewText">'. $project['description'] .'</p></div>';
        // content in het uitklapbare gedeelte
        $output .= '<div class="expandibleContentWrapper"> <h2>'. $project['title'] .'</h2> <img class="previewImage" src="'. $project['image'] .'" alt="'. $project['imageAlt'] .'"> <div class="expandibleContent">'. $project['content'] .'</div> </div> </div>';
    }};

    echo $output;
?>